"""Add user table

Revision ID: ee9a2ed18e80
Revises: bcce3f9e7662
Create Date: 2025-05-20 14:44:58.580309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9a2ed18e80'
down_revision = 'bcce3f9e7662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_users')
    with op.batch_alter_table('kk_demographics', schema=None) as batch_op:
        batch_op.alter_column('Respondent_No',
               existing_type=sa.TEXT(),
               type_=sa.String(length=14),
               nullable=False,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Civil_Status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Youth_Classification',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Youth_Age_Group',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Work_Status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Educational_Background',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Registered_SK_Voter',
               existing_type=sa.TEXT(),
               type_=sa.String(length=5),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Registered_National_Voter',
               existing_type=sa.TEXT(),
               type_=sa.String(length=5),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Attended_KK_Assembly',
               existing_type=sa.TEXT(),
               type_=sa.String(length=5),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Did_you_vote_last_SK_election',
               existing_type=sa.TEXT(),
               type_=sa.String(length=5),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('If_yeshow_many_times',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('If_No_Why',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.create_foreign_key(None, 'kk_profile', ['Respondent_No'], ['Respondent_No'])
        batch_op.drop_column('respondent_id')

    with op.batch_alter_table('kk_profile', schema=None) as batch_op:
        batch_op.alter_column('Respondent_No',
               existing_type=sa.TEXT(),
               type_=sa.String(length=14),
               existing_nullable=False)
        batch_op.alter_column('Date',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Last_Name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Middle_Name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('First_Name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Suffix',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Region',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Province',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Municipality',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Barangay',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Sex_Assigned_by_Birth',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Age',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Birthday',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Email_Address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Contact_No',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.drop_column('respondent_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('kk_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respondent_id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('Contact_No',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Email_Address',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Birthday',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Age',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Sex_Assigned_by_Birth',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Barangay',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Municipality',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Province',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Region',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Suffix',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('First_Name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Middle_Name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Last_Name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Date',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Respondent_No',
               existing_type=sa.String(length=14),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('kk_demographics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respondent_id', sa.INTEGER(), server_default=sa.text('(NULL)'), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('If_No_Why',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('If_yeshow_many_times',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Did_you_vote_last_SK_election',
               existing_type=sa.String(length=5),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Attended_KK_Assembly',
               existing_type=sa.String(length=5),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Registered_National_Voter',
               existing_type=sa.String(length=5),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Registered_SK_Voter',
               existing_type=sa.String(length=5),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Educational_Background',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Work_Status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Youth_Age_Group',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Youth_Classification',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Civil_Status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('Respondent_No',
               existing_type=sa.String(length=14),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text('(NULL)'))

    op.create_table('admin_users',
    sa.Column('admin_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.TEXT(), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False)
    )
    # ### end Alembic commands ###
